jobs:
samples-build-VS-2019:
runs-on: windows-2019

strategy:
  matrix:
    configuration: [Release, Debug]
    platform: [x86, x64]

steps:
  - uses: actions/checkout@v2

  - name: Setup MSBuild.exe
    uses: microsoft/setup-msbuild@v1.0.3
  
  - name: Use NuGet 5.2.0
    uses: nuget/setup-nuget@v1

  - name: Restore nuget packages for all solutions
    run: msbuild 'Samples/**/*.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }} /t:restore
  
  - name: Build all Sample solutions
    run: msbuild 'Samples/**/*.sln' /p:configuration=${{ matrix.configuration }} /p:platform=${{ matrix.platform }}
